testcontainter with auto termination
wiremock/wiremock-testcontainers-go pull request #30
Opened 2023-08-09 12:05 UTC by Vayras

As per the issue I have containerize the code the update code is in a new branch with same name as the issue
## References

- TODO

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [ ] The repository's code style is followed (see the contributing guide)
- [ ] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

![Screenshot 2023-08-09 172259](https://github.com/wiremock/wiremock-testcontainers-go/assets/89837102/e6607bca-92f3-4389-9f16-331fd3b37170)

2023-08-09 12:41 UTC, oleg-nenashev reviewed
Thanks for the pull request. I would actually expect not refactoring of a test case, but adding a new method in https://github.com/wiremock/wiremock-testcontainers-go/blob/main/tc-wiremock.go that makes  the test more simple 

It could be `RunContainerAndStopOnCleanup()` or so that takes the testing context as an extra argument

2023-08-09 13:37 UTC, Vayras commented
@oleg-nenashev thanks for your feedback , correct me if I'm wrong , the method needs to written in the _tc-wiremock.go_ and used in the _quickstart_test.go_?

2023-08-09 13:39 UTC, oleg-nenashev commented
@Vayras yup, this is correct. See https://github.com/wiremock/wiremock-testcontainers-go/pull/21 for inspiration

2023-08-09 13:43 UTC, Vayras commented
@oleg-nenashev should I implement these changes?

2023-08-09 13:55 UTC, oleg-nenashev commented
@Vayras this is an expectation in #27

2023-08-10 10:06 UTC, Vayras commented
@oleg-nenashev I have commited and pushed some changes using terminal can you please let me know if they reflect and are updated?

2023-08-15 15:37 UTC, oleg-nenashev requested changes
Thank you! It gets closer but we need to replace the `/hello` hardcoding by a proper mapping of parameters

2023-08-15 15:37 UTC, oleg-nenashev commented on tc-wiremock.go
> +		WithMappingFile("hello", mappingFileName),
That part needs to be parameterizable and, preferably, taking the same array as a `RunContainer` method

2023-08-15 17:14 UTC, Vayras commented on tc-wiremock.go
> +		WithMappingFile("hello", mappingFileName),
@oleg-nenashev Thank you for your feedback , will make these changes

2023-08-15 17:21 UTC, Vayras commented on tc-wiremock.go
> +		WithMappingFile("hello", mappingFileName),
![Screenshot 2023-08-15 224903](https://github.com/wiremock/wiremock-testcontainers-go/assets/89837102/3e913616-7784-458a-bd3c-5ec8740d37c9)
I think by adding an Id parameter the issue will be fixed

2023-08-16 21:16 UTC, oleg-nenashev reviewed
@Vayras I suggest keeping the original `RunContainerSomething(ctx context.Context, opts ...testcontainers.ContainerCustomizer)` interface so that the code is more flexible. You would need to just take this array as an argument and pass to the nested method

2023-08-17 10:11 UTC, oleg-nenashev commented
Thanks! Let's see how the CI runs, and happy to integrate it afterwards

2023-08-17 10:44 UTC, oleg-nenashev approved these changes
Thanks! I will update the README in the downstream PR, because there are a few other changes I wanted to land anyway

2023-08-17 10:44 UTC, merged

2023-08-17 10:53 UTC, Vayras commented
@oleg-nenashev It's truly been a great experience collaborating with you on this project. If the thought crosses your mind, I'd be honored to discuss the possibility of sponsorship for my work or even the potential of becoming a part of this organization. Please feel free to reach out anytime. I'm always eager to contribute my skills and expertise to address challenges as effectively as I can.

2023-08-17 11:55 UTC, oleg-nenashev commented
@Vayras from what I understand, you're just starting with Golang. I might be open to discuss various open source internship options in the future, but at the same time I want to highlight that asking for being paid for your work in the future after doing a single newcomer friendly contribution is unlikely to be perceived well by maintenance. So I recommend to revise the message above if you send it to other projects

2023-08-17 12:19 UTC, Vayras commented
@oleg-nenashev Thank you for addressing this  , finding an open source internship related to Golang would be very beneficial for me, and I think open source contribution , even with whatever little I do , keeps me motivated ,I'm fairly new to Golang , I have recently picked up learning this language any opportunity to get better at it is deeply appreciated.